config/routes.rb
Rails.application.routes.draw do
  get 'payments/webhook'
  devise_for :users
  root to: 'pages#home'

  resources :listings
  get '/about' => 'pages#about'
  get '/restricted', to: 'pages#restricted', as: 'restricted'

  post '/payments/webhook', to: 'payments#webhook'
  get 'payments/success', to: 'payments#success'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/feature.rb
class Feature < ApplicationRecord
    # belongs_to :listing
    has_many :feature_listings
    has_many :listings, through: :feature_listings
end

app/models/feature_listing.rb
class FeatureListing < ApplicationRecord
  belongs_to :listing
  belongs_to :feature
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :feature_listings, dependent: :destroy
  has_many :features, through: :feature_listings
  accepts_nested_attributes_for :feature_listings
  has_one_attached :picture
  before_save :remove_whitespace

private

  def remove_whitespace
    self.name = self.name.strip
    self.description = self.description.strip
  end

end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    belongs_to :listing
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :listings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_listing, only: %i[ show ]
  before_action :set_user_listing, only: [ :update, :edit, :destroy ]
  before_action :setup_form, only: [:new, :edit]

  # GET /listings or /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1 or /listings/1.json
  def show
    stripe_session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      client_reference_id: current_user ? current_user.id : nil,
      customer_email: current_user ? current_user.email : nil,

      line_items: [{
        price_data: {
          unit_amount: @listing.price.to_i * 100,
          currency: 'aud',
          product_data: {
            name: @listing.name,
            description: @listing.description
          },
        },
        quantity: 1
      }],

      payment_intent_data: {
        metadata: {
          listing_id: @listing.id,
          user_id: current_user ? current_user.id : nil
        }
      },
      mode: 'payment',
      success_url: "#{root_url}payments/success?listingId=#{@listing.id}",
      cancel_url: "#{root_url}listings"
    )

    @session_id = stripe_session.id
    pp stripe_session
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings or /listings.json
  def create
    # @listing = Listing.new(listing_params)

    @listing = current_user.listings.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: "Listing was successfully created." }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1 or /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: "Listing was successfully updated." }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1 or /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: "Listing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

#   def destroy
#     User.find(session[:user_id]).destroy      
#     session[:user_id] = nil         
#     redirect_to '/forsale' 
#   end  
# end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    def set_user_listing
      @listing = current_user.listings.find_by_id(params[:id])
      if @listing == nil 
        flash[:alert] = "You don't have permission to do that"
        redirect_to listings_path
      end
    end

    def setup_form
      @categories = Category.all
      @features = Feature.all
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:name, :picture, :description, :price, :category_id, feature_ids: [])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    before_action :authenticate_user!, only: [:restricted]

    def home
    end

    def about
    end

    def restricted
    end

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  
    skip_before_action :verify_authenticity_token, only: [:webhook]
  
    def webhook
      p params
      p "-----------------param------------------"
      payment_intent_id = params[:data][:object][:payment_intent]
      payment = Stripe::PaymentIntent.retrieve(payment_intent_id)
  
      listing_id = payment.metadata.listing_id
      buyer_id = payment.metadata.user_id
  
      p "-----------------receipt----------------"
      receipt_url = payment.charges.data[0].receipt_url

      p receipt_url
  
      Order.create(user_id: buyer_id, listing_id: listing_id, payment_intent_id: payment_intent_id, receipt_url: receipt_url)
  
      p params
      p "--------------------test----------------------"

      puts "test"
  
    end
  
    def success
      listing_id = params[:listingId]
      @listing = Listing.find(listing_id)
      # @purchase = Order.find_by_listing_id(params[:listingId])
      p "----------------------------------------"
      # p purchase
      p @listing
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

    def select_alert_type(input)
        case input
        when 'notice'
            return 'info'
        when 'success'
            return 'success'
        when 'error'
            return 'danger'
        when 'warning'
            return 'warning'
        else 
            return 'warning'
        end
    end

end

app/helpers/listings_helper.rb
module ListingsHelper

    def render_buy_button
        if current_user
            button = "<button data-stripe=\"payment\" class=\"btn btn-primary p-3\">Buy: $#{@listing.price}</button>"
        else
            button = "<button class=\"btn btn-secondary\" disabled>Log In to Buy</button>"
        end
        return button.html_safe
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QUart</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |type,message|  %>
      <div class="alert alert-<%= select_alert_type(type) %> >
        <%= message %>
      </div>
    <% end %>

    <%= render "shared/navbar" %>

    <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_with(model: listing) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
        <% listing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, class: "form-label mr-1" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :description, class: "form-label mr-1" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :price, class: "form-label mr-1" %>
    <%= form.text_field :price, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :category_id, class: "form-label mr-1" %>
    <%= form.select :category_id, @categories.map {|c| [c.name, c.id]} %>
  </div>

  <h5>Features</h5>
  <div class="form-check form-check-line">
    <%= form.collection_check_boxes :feature_ids, @features, :id, :name do |c| %>
      <%= c.label(class: "form-check-label") %>
      <%= c.check_box(class: "form-check mr-2") %>
    <% end %>
  </div>

  <h5 class='mb-3'>Picture</h5>
  <div class='form-group mb-3'>
    <%= form.label :picture, class: 'form-label' %>
    <%= form.file_field :picture, accepts: "image/png,image/jpg,image/jpeg", class: 'form-control-file' %>
    <br>
    <small class='form-text text-muted'>PNG, JPG and JPEG only</small>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<footer class="copyright">
            <p>Copyright &#169 QUart 2021 – All rights reserved</p>
    </footer>
    <script src="https://unpkg.com/ionicons@5.4.0/dist/ionicons.js"></script>
    <script src="javascript/main.js"></script>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing, categories: @categories, features: @features %>

<%= link_to 'Show', @listing %>
<%= link_to 'Back', listings_path %>

<footer class="copyright">
            <p>Copyright &#169 QUart 2021 – All rights reserved</p>
    </footer>
    <script src="https://unpkg.com/ionicons@5.4.0/dist/ionicons.js"></script>
    <script src="javascript/main.js"></script>

app/views/listings/index.html.erb
<h1 class="hero-title text-center">Gallery / Store</h1>

<div class='container'>
  <div class='row row-cols-sm-1 row-cols-md-2 row-cols-lg-4'>
    <% @listings.each do |listing| %>
      <div class='col mb-4'>
        <div class='card border-dark h-100'>
          <%= image_tag listing.picture, class: "card-img top thumbnail" if listing.picture.attached?  %>
          <div class='card-body'>
            <h5><%= listing.name %></h5>
            <h6 class='card-subtitle text-muted'>Added <%= time_ago_in_words(listing.created_at) %> ago</h6>
            <p class='card-text text-secondary text-truncate'><%= listing.description %></p>
            <div class='d-flex justify-content-between'>
              <%= link_to "See More", listing_path(listing.id), class: "btn btn-primary" %>
              <h5>$<%= listing.price %></h5>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<footer class="copyright">
  <p>Copyright &#169 QUart 2021 – All rights reserved</p>
</footer>
<script src="https://unpkg.com/ionicons@5.4.0/dist/ionicons.js"></script>
<script src="javascript/main.js"></script>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing, categories: @categories %>

<%= link_to 'Back', listings_path %>

<footer class="copyright">
            <p>Copyright &#169 QUart 2021 – All rights reserved</p>
    </footer>
    <script src="https://unpkg.com/ionicons@5.4.0/dist/ionicons.js"></script>
    <script src="javascript/main.js"></script>

app/views/listings/show.html.erb
<div class='container d-flex flex-column flex-md-row px-2 my-2 my-md-5'>
    <div class='col-12 col-md-7 col-lg-8 p-0 pr-md-3'> 
      <div class='col-12 p-0 mb-4'>
        <%= image_tag @listing.picture, class: "card-img top thumbnail" if @listing.picture.attached? %>
      </div>
    </div>
    <div class= 'col-lg-4 p-0 mx-2 d-md-block'>
      <h1 class='mb-sm-2 mb-md-5'><%=@listing.name%></h1>
      <% @listing.features.each do |feature| %>
        <span class='badge bg-info text-dark'><%=feature.name%></span>
      <%end%>
      <p class='blockquote mt-2'><%=@listing.description%></p>
      <%= render_buy_button %>
    </div>
  </div>
</div>
<div class='container'>
  <div class ='d-flex justify-content-evenly'>
  <%=link_to "Edit", edit_listing_path(@listing.id), class: "btn btn-warning mr-3" if current_user && current_user.id == @listing.user_id%>
  <%=button_to "Delete", @listing, method: :delete, data: {confirm: "Are you sure?"} , class: "btn btn-danger mr-3" if current_user && current_user.id == @listing.user_id%>
  </div>
</div>

<script src="https://js.stripe.com/v3/"></script>
<script>
  document
    .querySelector("[data-stripe='payment']")
    .addEventListener("click", () => {
      const stripe = Stripe(
        "<%= Rails.application.credentials.dig(:stripe, :public_key) %>"
      )
      stripe.redirectToCheckout({
        sessionId: "<%= @session_id %>"
      })
    })
</script>
<!-------------footer--------->
<footer class="copyright">
  <p>Copyright &#169 QUart 2021 – All rights reserved</p>
</footer>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="css/style.css">
    <link href="https://fonts.googleapis.com/css2?family=Allura&family=Mr+Dafoe&family=Reenie+Beanie&display=swap" rel="stylesheet">
    <title>QUart</title>
</head>
<body>
    <div class="about-container">
        <h1>About</h1>
        <h3>QUart was formed in 2021 to showcase the very best art in Queensland, Australia and connects the artists directly with art-lovers worldwide.</h3>
    </div>

<!-------------footer--------->
        <footer class="copyright">
            <p>Copyright &#169 QUart 2021 – All rights reserved</p>
    </footer>
    <script src="https://unpkg.com/ionicons@5.4.0/dist/ionicons.js"></script>
    <script src="javascript/main.js"></script>
</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="css/style.css">
    <link href="https://fonts.googleapis.com/css2?family=Allura&family=Mr+Dafoe&family=Reenie+Beanie&display=swap" rel="stylesheet">
    <title>QUart</title>
</head>
<body>
    <%# <header>
        <div class="overlay"></div> %>
        <%# <nav>
            <h2>QUart</h2>
            <ul>
                <li><a href="index.html">Home</a></li>
                <li><a href="shop.html">Shop</a></li>
                <li><a href="about.html">About</a></li>
                <li><a href="art.html">Art</a></li>
                <li><a href="contact.html">Contact</a></li>
                <li class="cart">
                    <a href="cart.html">
                        <ion-icon name="basket"></ion-icon>Cart<span>0</span>
                    </a>
                </li>
            </ul>
        </nav>
    </header>
</div> %>
    <div class="main-image">
        <%= image_tag asset_path("dsc00054.jpg") %>
        <%= image_tag asset_path("dsc00055.jpg") %>
        <%= image_tag asset_path("dark-rocks.jpg") %>
        <%= image_tag asset_path("3-while-the-sun-shines.jpg") %>
    </div>
<!-------------footer--------->
        <footer class="copyright">
            <p>Copyright &#169 QUart 2021 – All rights reserved</p>
    </footer>
    <script src="https://unpkg.com/ionicons@5.4.0/dist/ionicons.js"></script>
    <script src="javascript/main.js"></script>
</body>
</html>

app/views/pages/restricted.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="css/style.css">
    <link href="https://fonts.googleapis.com/css2?family=Allura&family=Mr+Dafoe&family=Reenie+Beanie&display=swap" rel="stylesheet">
    <title>QUart</title>
</head>
<body>
    <div class="restricted-container">
        <h1>Dashboard</h1>
        <h3>Super sensitive restricted account information!</h3>
    </div>

<!-------------footer--------->
        <footer class="copyright">
            <p>Copyright &#169 QUart 2021 – All rights reserved</p>
    </footer>
    <script src="https://unpkg.com/ionicons@5.4.0/dist/ionicons.js"></script>
    <script src="javascript/main.js"></script>
</body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand sticky-top navbar-dark bg-primary">
    <div class="container-fluid">
        <%= link_to "QUart", root_path, class: "navbar-brand" %>
        <ul class="navbar-nav">
            <li class="navbar-item mr-5-lg">
                <%= link_to "See Listings", listings_path, class: "nav-link" %>
            </li>

            <% if user_signed_in? %>
                <li class="navbar-item mr-5-lg">
                    <%= link_to "Create Listing", new_listing_path, class: "nav-link" %>
                </li>
                <li class="navbar-item mr-5-lg">
                    <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
                </li>
            <% else %>
                <li class="navbar-item mr-5-lg">
                    <%= link_to "Login", new_user_session_path, class: "nav-link" %>
                </li>
                <li class="navbar-item mr-5-lg">
                    <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
                </li>
            <% end %>
        </ul>
    </div>
</nav>

app/views/payments/success.html.erb
<div class="payment-success">
<h1>Payment Successful!</h1><br>

<p>You purchased <%= @listing.name %> </p>

<p>Congratulations, you paid. <%= @listing.price %> </p>
</div>

<!-------------footer--------->
<footer class="copyright">
    <p>Copyright &#169 QUart 2021 – All rights reserved</p>
</footer>
<%# <%= link_to "Receipt", @purchase.receipt_url, target: :_blank %>

app/views/payments/webhook.html.erb
<h1>Payments#webhook</h1>
<p>Find me in app/views/payments/webhook.html.erb</p>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light" style="background-color: #a3d2ca;>
    <div class="container-fluid">
    <div class="quart-logo">
        <%= link_to "QUart", root_path, class: "navbar-brand" %>
        </div>
        <ul class="navbar-nav">
            <li class="navbar-item mr-5-lg">
                <%= link_to "Gallery / Store", listings_path, class: "nav-link" %>
                <%= link_to "About", about_path, class: "nav-link" %>
            </li>

            <% if user_signed_in? %>
                <li class="navbar-item mr-5-lg">
                    <%= link_to "Create Listing", new_listing_path, class: "nav-link" %>
                    <span class='nav-greeting'> <%= "Welcome back, #{current_user.email}"%> </span>
                </li>
                <li class="navbar-item mr-5-lg">
                    <%= button_to "Log Out", destroy_user_session_path, :method => :delete, class: "nav-link" %>
                </li>
            <% else %>
                <li class="navbar-item mr-5-lg">
                    <%= link_to "Login", new_user_session_path, class: "nav-link" %>
                </li>
                <li class="navbar-item mr-5-lg">
                    <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
                </li>
            <% end %>
        </ul>
    </div>
</nav>